
project_id = "byvbunvegjwzgytavgkv"

[functions.database-functions]
verify_jwt = false

[functions.initialize-database]
verify_jwt = false

[functions.telemetry-api]
verify_jwt = false

[functions.get-devices]
verify_jwt = false

